name: amip-paper-2023
dependencies:
  - pip
  - json_tricks>=3.11.2
  - numpy>=1.16.1
  - matplotlib>=3.0.1
  - numpy>=1.16.1
  - scipy>=1.0.1
  - pandas
  - jupyter>=1.0.0
  - scikit-learn
  - pip:
    - git+https://github.com/rgiordan/paragami@master#egg=paragami
    - git+https://github.com/rgiordan/vittles@master#egg=vittles
    - git+https://github.com/HIPS/autograd/@master#egg=autograd
    - -e .


  # - jupyter-client>=5.2.4
  # - jupyter-console>=6.0.0
  # - jupyter-contrib-core>=0.3.3
  # - jupyter-contrib-nbextensions>=0.5.1
  # - jupyter-core>=4.4.0
  # - jupyter-highlight-selected-word>=0.2.0
  # - jupyter-latex-envs>=1.4.6
  # - jupyter-nbextensions-configurator>=0.4.1
  # - scikit-learn>=0.0

#  - sklearn>=0.0

#  - paragami @ git+https://github.com/rgiordan/paragami@log_det_jac#egg=paragami
#  - vittles @ git+https://github.com/rgiordan/vittles@master#egg=vittles
#  - autograd @ git+https://github.com/HIPS/autograd/@master#egg=autograd
 