 # conda env create -f environment.yml
 # python3 -m ipykernel install --user --name=amip-paper-2023
 # python3 -m pip install ~/Documents/git_repos/AdversarialInfluenceWorkbench/examples/microcredit_mixture